const MenuItems = [
  {
    Mid: 1,
    category: "Pizzas",
    items: [
      {
        id: 1,
        image: "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
        name: "Chicken Supreme",
        Menu_categoryid: 1,
        price: 599,
        description: "Chicken tikka, cheese and onions",
      },
      {
        id: 2,
        image: "https://www.themealdb.com/images/media/meals/0jv5gx1661040802.jpg",
        name: "Peri Peri Pizza",
        Menu_categoryid: 1,
        price: 500,
        description: "Chicken tikka, chicken sausages",
      },
      {
        id: 3,
        image: "https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg",
        name: "Peri Peri Pizza",
        Menu_categoryid: 1,
        price: 500,
        description: "Chicken tikka, chicken sausages",
      },
      {
        id:4,
        image: "https://www.themealdb.com/images/ingredients/Chicken.png",
        name: "Smoked Chicken",
        Menu_categoryid: 1,
        price: 678,
        description: "Smoked chicken, cheese, mushrooms and onions",
      },
    ],
  },

  {
    Mid: 2,
    category: "Burgers",
    items: [

      {
        id: 5,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Crispy Chicken Burger",
        Menu_categoryid: 2,
        price: 448,
        description: "Chicken tikka, chicken sausages",
      },
      {
        id: 6,
        image: "https://www.themealdb.com/images/media/meals/k420tj1585565244.jpg",
        name: "Peri Peri Chicken",
        Menu_categoryid: 2,
        price: 698,
        description: "chicken sausages mushrooms and onions",
      },
      {
        id: 7,
        image: "https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg",
        name: "Beef Cheese Burger",
        Menu_categoryid: 2,
        price: 700,
        description: "Special cheese, thousand island sauce and crispy onions",
      },
      {
        id: 8,
        image: "https://www.themealdb.com/images/media/meals/k420tj1585565244.jpg",
        name: "Double Beef Burger",
        Menu_categoryid: 2,
        price: 750,
        description: "Two beef patty, double cheese, lettuce and tomatoes",
      },
    ],
  },
  {
    Mid: 3,
    category: "Sandwiches",
    items: [
      {
        id: 9,
        image: "https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg",
        name: "Chicken Tikka Sandwich",
        Menu_categoryid: 3,
        price: 398,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 10,
        image: "https://www.themealdb.com/images/media/meals/xr0n4r1576788363.jpg",
        name: "Chicken BBQ Sandwich",
        Menu_categoryid: 3,
        price: 398,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 11,
        image: "https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg",
        name: "Chicken Fajita Sandwich",
        Menu_categoryid: 3,
        price: 400,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 12,
        image: "https://www.themealdb.com/images/media/meals/b5ft861583188991.jpg",
        name: "Peri Peri Sandwich",
        Menu_categoryid: 3,
        price: 450,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
    ],
  },
  {
    Mid: 4,
    category: "Fried Items",
    items: [
      {
        id: 13,
        image: "https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg",
        name: "Hot Wings",
        Menu_categoryid: 4,
        price: 298,
        Menu_id: 2,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 14,
        image: "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
        name: "Crispy Chicken Piece",
        Menu_categoryid: 4,
        price: 298,
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      {
        id:15,
        image: "https://www.themealdb.com/images/media/meals/y2irzl1585563479.jpg",
        name: "Crisparatha",
        Menu_categoryid: 4,
        price: 298,
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      {
        id: 16,
        image: "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
        name: "Crisparatha",
        Menu_categoryid: 5,
        price: 298,
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      
    ],
  },
  {
    Mid: 5,
    category: "Drinks",
    items: [
      {
        id: 17,
        image: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
        name: "Mango Shake",
        Menu_categoryid: 5,
        price: 150,
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 18,
        image: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
        name: "Oreo Chocolate Shake",
        Menu_categoryid: 5,
        price: 150,
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 19,
        image: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
        name: "Apple Juice",
        Menu_categoryid: 5,
        price: 150,
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
    
      {
        id: 20,
        image: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
        name: "Banana Date Mix",
        Menu_categoryid: 5,
        price: 150,
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 21,
        image: "https://www.themealdb.com/images/media/meals/uuxwvq1483907861.jpg",
        name: "Apple Date Mix Shake",
        Menu_categoryid: 5,
        price: 150,
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      
    ],
  },
  {
    Mid: 6,
    category: "Biryani",
    items: [
      {
        id: 22,
        image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
        name: "Biryani",
        Menu_categoryid: 6,
        price: 200,
        Menu_id: 3,
        description: "Chicken Biryani",
      },
      {
        id: 23,
        image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
        name: "Chicken Pulao",
        Menu_categoryid: 6,
        price: 250,
        Menu_id: 3,
        description: "Chicken Pulao",
      },
      {
        id: 24,
        image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
        name: "Sada Biryani",
        Menu_categoryid: 6,
        price: 300,
        Menu_id: 3,
        description: "Sada Biryani",
      },
      {
        id: 25,
        image: "https://www.themealdb.com/images/media/meals/xrttsx1487339558.jpg",
        name: "Shami Kabab",
        Menu_categoryid: 7,
        price: 80 ,
        Menu_id: 3,
        description: "Shami Kabab",
      },
      
    ],
  },
  {
    Mid: 7,
    category: "Sides",
    items: [
      {
        id: 26,
        image: "https://www.themealdb.com/images/media/meals/usywpp1511189717.jpg",
        name: "Salad",
        Menu_categoryid: 7,
        price: 90 ,
        Menu_id: 3,
        description: "Salad",
      },
      {
        id: 27,
        image: "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
        name: "Raita",
        Menu_categoryid: 7,
        price: 90 ,
        Menu_id: 3,
        description: "Raita",
      },
      {
        id: 28,
        image: "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
        name: "Chicken & Drink",
        Menu_categoryid: 8,
        price: 800,
        Menu_id: 4,
        description: "Chicken & Drink",
      },
    
      
    ],
  },
  {
    Mid: 8,
    category: "Popular",
    items: [
      {
        id: 29,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Family Share Bag",
        Menu_categoryid: 8,
        price: 560,
        Menu_id: 4,
        description: "Family Share Bag",
      },
      {
        id: 30,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Plus",
        Menu_categoryid: 8,
        price: 350,
        Menu_id: 4,
        description: "Chicken Plus",
      },
      {
        id: 31,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Budget Share Bag",
        Menu_categoryid: 8,
        price: 350,
        Menu_id: 4,
        description: "Budget Share Bag",
      },
    
      
    ],
  },
  {
    Mid: 9,
    category: "Brownies",
    items: [
      {
        id: 32,
        image: "https://www.themealdb.com/images/media/meals/uttuxy1511382180.jpg",
        name: "Nutella Brownie",
        Menu_categoryid: 9,
        price: 350,
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      {
        id: 33,
        image: "https://www.themealdb.com/images/media/meals/rqvwxt1511384809.jpg",
        name: "Belgian Malt Brownie",
        Menu_categoryid: 9,
        price: 400,
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      {
        id: 34,
        image: "https://www.themealdb.com/images/media/meals/yypvst1511386427.jpg",
        name: "Cadbury Brownie",
        Menu_categoryid: 9,
        price: 550,
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      
    ],
  },
  {
    Mid: 10,
    category: "Cakes",
    items: [
      {
        id: 36,
        image: "https://www.themealdb.com/images/media/meals/1d85821576790598.jpg",
        name: "Belgian Chocolate",
        Menu_categoryid: 10,
        price: 100,
        Menu_id: 5,
        description: "2.5 Pounds. Made from the purest Belgian chocolate",
      },
      {
        id: 37,
        image: "https://www.themealdb.com/images/media/meals/rqvwxt1511384809.jpg",
        name: "Ferrero Classic Cake",
        Menu_categoryid: 10,
        price: 105,
        Menu_id: 5,
        description:
          "2.5 Pounds. Made from 100% ferrero hazelnut chocolate & roasted nuts",
      },
      {
        id: 38,
        image: "https://www.themealdb.com/images/media/meals/vrspxv1511722107.jpg",
        name: "Nutella Cake",
        Menu_categoryid: 10,
        price: 150,
        Menu_id: 5,
        description: "2.5 Pounds. Made from 100% nutella & imported cream",
      },
      {
        id: 39,
        image: "https://www.themealdb.com/images/media/meals/twspvx1511784937.jpg",
        name: "Three Milk Cakee",
        Menu_categoryid: 10,
        price: 200,
        Menu_id: 5,
        description: "2.5 Pounds. Vanilla sponge cake in three kinds of milk",
      },
      
    ],
  },
  
];

export default MenuItems;
