const MenuItems = [
  {
    Mid: 1,
    category: "Pizzas",
    items: [
      {
        id: 85,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Supreme",
        Menu_categoryid: 1,
        price: "599 PKR",
        description: "Chicken tikka, cheese and onions",
      },
      {
        id: 86,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Peri Peri Pizza",
        Menu_categoryid: 1,
        price: "500 PKR",
        description: "Chicken tikka, chicken sausages",
      },
      {
        id: 87,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Peri Peri Pizza",
        Menu_categoryid: 1,
        price: "500 PKR",
        description: "Chicken tikka, chicken sausages",
      },
      {
        id:88,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Smoked Chicken",
        Menu_categoryid: 1,
        price: "678 PKR",
        description: "Smoked chicken, cheese, mushrooms and onions",
      },
    ],
  },

  {
    Mid: 2,
    category: "Burgers",
    items: [

      {
        id: 34,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Crispy Chicken Burger",
        Menu_categoryid: 2,
        price: "448 PKR",
        description: "Chicken tikka, chicken sausages",
      },
      {
        id: 35,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Peri Peri Chicken",
        Menu_categoryid: 2,
        price: "698 PKR",
        description: "chicken sausages mushrooms and onions",
      },
      {
        id: 36,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Beef Cheese Burger",
        Menu_categoryid: 2,
        price: "700 PKR",
        description: "Special cheese, thousand island sauce and crispy onions",
      },
      {
        id: 37,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Double Beef Burger",
        Menu_categoryid: 2,
        price: "750 PKR",
        description: "Two beef patty, double cheese, lettuce and tomatoes",
      },
    ],
  },
  {
    Mid: 3,
    category: "Sandwiches",
    items: [
      {
        id: 38,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Tikka Sandwich",
        Menu_categoryid: 3,
        price: "398 PKR",
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 39,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken BBQ Sandwich",
        Menu_categoryid: 3,
        price: "398 PKR",
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 40,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Fajita Sandwich",
        Menu_categoryid: 3,
        price: "400 PKR",
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 41,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Peri Peri Sandwich",
        Menu_categoryid: 3,
        price: "450 PKR",
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
    ],
  },
  {
    Mid: 4,
    category: "Fried Items",
    items: [
      {
        id: 41,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Hot Wings",
        Menu_categoryid: 4,
        price: "298 PKR",
        Menu_id: 2,
        description: "Chicken tikka, onion, lettuce, ketchup and mayo",
      },
      {
        id: 42,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Crispy Chicken Piece",
        Menu_categoryid: 4,
        price: "298 PKR",
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      {
        id: 43,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Crisparatha",
        Menu_categoryid: 4,
        price: "298 PKR",
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      {
        id: 44,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Crisparatha",
        Menu_categoryid: 5,
        price: "298 PKR",
        Menu_id: 2,
        description: "chicken Piece with a crisp layer",
      },
      
    ],
  },
  {
    Mid: 5,
    category: "Drinks",
    items: [
      {
        id: 45,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Mango Shake",
        Menu_categoryid: 5,
        price: "150 PKR",
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 46,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Oreo Chocolate Shake",
        Menu_categoryid: 5,
        price: "150 PKR",
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 47,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Apple Juice",
        Menu_categoryid: 5,
        price: "150 PKR",
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
    
      {
        id: 48,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Banana Date Mix",
        Menu_categoryid: 5,
        price: "150 PKR",
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      {
        id: 49,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Apple Date Mix Shake",
        Menu_categoryid: 5,
        price: "150 PKR",
        Menu_id: 2,
        description: "Mediuml/large serving",
      },
      
    ],
  },
  {
    Mid: 6,
    category: "Biryani",
    items: [
      {
        id: 50,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Biryani",
        Menu_categoryid: 6,
        price: "200 PKR",
        Menu_id: 3,
        description: "Chicken Biryani",
      },
      {
        id: 51,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Pulao",
        Menu_categoryid: 6,
        price: "250 PKR",
        Menu_id: 3,
        description: "Chicken Pulao",
      },
      {
        id: 52,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Sada Biryani",
        Menu_categoryid: 6,
        price: "300 PKR",
        Menu_id: 3,
        description: "Sada Biryani",
      },
      {
        id: 53,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Shami Kabab",
        Menu_categoryid: 7,
        price: "80 PKR",
        Menu_id: 3,
        description: "Shami Kabab",
      },
      
    ],
  },
  {
    Mid: 7,
    category: "Sides",
    items: [
      {
        id: 54,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Salad",
        Menu_categoryid: 7,
        price: "90 PKR",
        Menu_id: 3,
        description: "Salad",
      },
      {
        id: 55,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Raita",
        Menu_categoryid: 7,
        price: "90 PKR",
        Menu_id: 3,
        description: "Raita",
      },
      {
        id: 56,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken & Drink",
        Menu_categoryid: 8,
        price: "800 PKR",
        Menu_id: 4,
        description: "Chicken & Drink",
      },
    
      
    ],
  },
  {
    Mid: 8,
    category: "Popular",
    items: [
      {
        id: 57,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Family Share Bag",
        Menu_categoryid: 8,
        price: "560 PKR",
        Menu_id: 4,
        description: "Family Share Bag",
      },
      {
        id: 58,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Chicken Plus",
        Menu_categoryid: 8,
        price: "350 PKR",
        Menu_id: 4,
        description: "Chicken Plus",
      },
      {
        id: 59,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Budget Share Bag",
        Menu_categoryid: 8,
        price: "350 PKR",
        Menu_id: 4,
        description: "Budget Share Bag",
      },
    
      
    ],
  },
  {
    Mid: 9,
    category: "Brownies",
    items: [
      {
        id: 60,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Nutella Brownie",
        Menu_categoryid: 9,
        price: "350 PKR",
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      {
        id: 61,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Belgian Malt Brownie",
        Menu_categoryid: 9,
        price: "400 PKR",
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      {
        id: 62,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Cadbury Brownie",
        Menu_categoryid: 9,
        price: "550 PKR",
        Menu_id: 5,
        description: "Every shape, any size and irresistibly delicious",
      },
      
    ],
  },
  {
    Mid: 10,
    category: "Cakes",
    items: [
      {
        id: 63,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Belgian Chocolate",
        Menu_categoryid: 10,
        price: "1000 PKR",
        Menu_id: 5,
        description: "2.5 Pounds. Made from the purest Belgian chocolate",
      },
      {
        id: 64,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Ferrero Classic Cake",
        Menu_categoryid: 10,
        price: "1050 PKR",
        Menu_id: 5,
        description:
          "2.5 Pounds. Made from 100% ferrero hazelnut chocolate & roasted nuts",
      },
      {
        id: 65,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Nutella Cake",
        Menu_categoryid: 10,
        price: "1500 PKR",
        Menu_id: 5,
        description: "2.5 Pounds. Made from 100% nutella & imported cream",
      },
      {
        id: 66,
        image: "https://spoonacular.com/recipeImages/579246-556x370.jpg",
        name: "Three Milk Cakee",
        Menu_categoryid: 10,
        price: "2000 PKR",
        Menu_id: 5,
        description: "2.5 Pounds. Vanilla sponge cake in three kinds of milk",
      },
      
    ],
  },
  
];

export default MenuItems;
