const MenuItems = [
  {
    MenuItemid: 1,
    image:"",
    name: "Chicken Supreme",
    Menu_categoryid: 1,
    price: "599 PKR",
    description: "Chicken tikka, cheese and onions",

  },

  {
    MenuItemid: 2,
    image:"",
    name: "Peri Peri Pizza",
    Menu_categoryid: 1,
    price: "500 PKR",
    description: "Chicken tikka, chicken sausages",
  },
  {
    MenuItemid: 3,
    image:"",
    name: "Super Supreme Beef",
    Menu_categoryid: 1,
    price: "558 PKR",
    description: "Beef, pepperoni, black olives, cheese",
  },
  {
    MenuItemid: 4,
    image:"",
    name: "Smoked Chicken",
    Menu_categoryid: 1,
    price: "678 PKR",
    description: "Smoked chicken, cheese, mushrooms and onions",
  },
  {
    MenuItemid: 5,
    image:"",
    name: "Crispy Chicken Burger",
    Menu_categoryid: 2,
    price: "448 PKR",
    description: "Chicken tikka, chicken sausages",
  },
  {
    MenuItemid: 6,
    image:"",
    name: "Peri Peri Chicken Burger",
    Menu_categoryid: 2,
    price: "698 PKR",
    description: "chicken sausages mushrooms and onions",
  },
  {
    MenuItemid: 7,
    image:"",
    name: "Beef Cheese Burger",
    Menu_categoryid: 2,
    price: "700 PKR",
    description: "Special cheese, thousand island sauce and crispy onions",
  },
  {
    MenuItemid: 8,
    image:"",
    name: "Double Beef Burger",
    Menu_categoryid: 2,
    price: "750 PKR",
    description: "Two beef patty, double cheese, lettuce and tomatoes",
  },
  {
    MenuItemid: 9,
    image:"",
    name: "Chicken Tikka Sandwich",
    Menu_categoryid: 3,
    price: "398 PKR",
    description: "Chicken tikka, onion, lettuce, ketchup and mayo",
  },
  {
    MenuItemid: 10,
    image:"",
    name: "Chicken BBQ Sandwich",
    Menu_categoryid: 3,
    price: "398 PKR",
    description: "Chicken tikka, onion, lettuce, ketchup and mayo",
  },
  {
    MenuItemid: 11,
    image:"",
    name: "Chicken Fajita Sandwich",
    Menu_categoryid: 3,
    price: "400 PKR",
    description: "Chicken tikka, onion, lettuce, ketchup and mayo",
  },
  {
    MenuItemid: 12,
    image:"",
    name: "Peri Peri Sandwich",
    Menu_categoryid: 3,
    price: "450 PKR",
    description: "Chicken tikka, onion, lettuce, ketchup and mayo",
  },
  {
    MenuItemid: 13,
    image:"",
    name: "Hot Wings",
    Menu_categoryid: 4,
    price: "298 PKR",
    Menu_id: 2,
    description: "Chicken tikka, onion, lettuce, ketchup and mayo",
  },
  {
    MenuItemid: 14,
    image:"",
    name: "Crispy Chicken Piece",
    Menu_categoryid: 4,
    price: "298 PKR",
    Menu_id: 2,
    description: "chicken Piece with a crisp layer",
  },
  {
    MenuItemid: 15,
    image:"",
    name: "Crisparatha",
    Menu_categoryid: 4,
    price: "298 PKR",
    Menu_id: 2,
    description: "chicken Piece with a crisp layer",
  },
  {
    MenuItemid: 16,
    image:"",
    name: "Crisparatha",
    Menu_categoryid: 5,
    price: "298 PKR",
    Menu_id: 2,
    description: "chicken Piece with a crisp layer",
  },
  {
    MenuItemid: 17,
    image:"",
    name: "Mango Shake",
    Menu_categoryid: 5,
    price: "150 PKR",
    Menu_id: 2,
    description: "Mediuml/large serving",
  },
  {
    MenuItemid: 18,
    image:"",
    name: "Oreo Chocolate Shake",
    Menu_categoryid: 5,
    price: "150 PKR",
    Menu_id: 2,
    description: "Mediuml/large serving",
  },
  {
    MenuItemid: 19,
    image:"",
    name: "Apple Juice",
    Menu_categoryid: 5,
    price: "150 PKR",
    Menu_id: 2,
    description: "Mediuml/large serving",
  },

  {
    MenuItemid: 20,
    image:"",
    name: "Banana Date Mix Shake",
    Menu_categoryid: 5,
    price: "150 PKR",
    Menu_id: 2,
    description: "Mediuml/large serving",
  },
  {
    MenuItemid: 21,
    image:"",
    name: "Apple Date Mix Shake",
    Menu_categoryid: 5,
    price: "150 PKR",
    Menu_id: 2,
    description: "Mediuml/large serving",
  },
  {
    MenuItemid: 22,
    image:"",
    name: "Biryani",
    Menu_categoryid: 6,
    price: "200 PKR",
    Menu_id: 3,
    description: "Chicken Biryani",
  },
  {
    MenuItemid: 23,
    image:"",
    name: "Chicken Pulao",
    Menu_categoryid: 6,
    price: "250 PKR",
    Menu_id: 3,
    description: "Chicken Pulao",
  },
  {
    MenuItemid: 24,
    image:"",
    name: "Sada Biryani",
    Menu_categoryid: 6,
    price: "300 PKR",
    Menu_id: 3,
    description: "Sada Biryani",
  },
  {
    MenuItemid: 25,
    image:"",
    name: "Shami Kabab",
    Menu_categoryid: 7,
    price: "80 PKR",
    Menu_id: 3,
    description: "Shami Kabab",
  },
  {
    MenuItemid: 26,
    image:"",
    name: "Salad",
    Menu_categoryid: 7,
    price: "90 PKR",
    Menu_id: 3,
    description: "Salad",
  },
  {
    MenuItemid: 27,
    image:"",
    name: "Raita",
    Menu_categoryid: 7,
    price: "90 PKR",
    Menu_id: 3,
    description: "Raita",
  },
  {
    MenuItemid: 28,
    image:"",
    name: "Chicken & Drink",
    Menu_categoryid: 8,
    price: "800 PKR",
    Menu_id: 4,
    description: "Chicken & Drink",
  },
  {
    MenuItemid: 29,
    image:"",
    name: "Family Share Bag",
    Menu_categoryid: 8,
    price: "560 PKR",
    Menu_id: 4,
    description: "Family Share Bag",
  },
  {
    MenuItemid: 30,
    image:"",
    name: "Chicken Plus",
    Menu_categoryid: 8,
    price: "350 PKR",
    Menu_id: 4,
    description: "Chicken Plus",
  },
  {
    MenuItemid: 31,
    image:"",
    name: "Budget Share Bag",
    Menu_categoryid: 8,
    price: "350 PKR",
    Menu_id: 4,
    description: "Budget Share Bag",
  },
  {
    MenuItemid: 32,
    image:"",
    name: "Nutella Brownie",
    Menu_categoryid: 9,
    price: "350 PKR",
    Menu_id: 5,
    description: "Every shape, any size and irresistibly delicious",
  },
  {
    MenuItemid: 33,
    image:"",
    name: "Belgian Malt Brownie",
    Menu_categoryid: 9,
    price: "400 PKR",
    Menu_id: 5,
    description: "Every shape, any size and irresistibly delicious",
  },
  {
    MenuItemid: 34,
    image:"",
    name: "Cadbury Brownie",
    Menu_categoryid: 9,
    price: "550 PKR",
    Menu_id: 5,
    description: "Every shape, any size and irresistibly delicious",
  },
  {
    MenuItemid: 35,
    image:"",
    name: "Belgian Chocolate Cake",
    Menu_categoryid: 10,
    price: "1000 PKR",
    Menu_id: 5,
    description: "2.5 Pounds. Made from the purest Belgian chocolate",
  },
  {
    MenuItemid: 36,
    image:"",
    name: "Ferrero Classic Cake",
    Menu_categoryid: 10,
    price: "1050 PKR",
    Menu_id: 5,
    description:
      "2.5 Pounds. Made from 100% ferrero hazelnut chocolate & roasted nuts",
  },
  {
    MenuItemid: 37,
    image:"",
    name: "Nutella Cake",
    Menu_categoryid: 10,
    price: "1500 PKR",
    Menu_id: 5,
    description: "2.5 Pounds. Made from 100% nutella & imported cream",
  },
  {
    MenuItemid: 38,
    image:"",
    name: "Three Milk Cakee",
    Menu_categoryid: 10,
    price: "2000 PKR",
    Menu_id: 5,
    description: "2.5 Pounds. Vanilla sponge cake in three kinds of milk",
  },
];

export default MenuItems;
