const Restaurants = [
  {
    id: 1,
    image: "static/images/pizza.jpeg",
    name: "Jalal Sons -Model Town ",
    Restaurant_category_id: 1,
    Deliveryfee: "70 PKR",
    Rating: "4.2/5",
    Menu: 1,
    Cityid: 1,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },

  {
    id: 2,
    image: "static/images/optp.jpeg",
    name: "OPTP- Faisal Town",
    Restaurant_category_id: 1,
    Deliveryfee: "80 PKR",
    Rating: "4.1/5",
    Menu: 2,
    Cityid: 11,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 3,
    image: "static/images/jalalsons.jpeg",
    name: "Papa Johns ",
    Restaurant_category_id: 1,
    Deliveryfee: "90 PKR",
    Rating: "4.5/5",
    Menu: 3,
    Cityid: 1,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 4,
    image: "static/images/burger.jpeg",
    name: "Subway - Faisal Town",
    Restaurant_category_id: 1,
    Deliveryfee: "100 PKR",
    Rating: "4.5/5",
    Menu: 4,
    Cityid: 1,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 5,
    image: "static/images/pizza.jpeg",
    name: "Broadway Pizza",
    Restaurant_category_id: 1,
    Deliveryfee: "120 PKR",
    Rating: "4.7/5",
    Menu: 5,
    Cityid: 5,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 6,
    image: "static/images/kithchen.jpeg",
    name: "Ghar se Ghar Tak",
    Restaurant_category_id: 2,
    Deliveryfee: "50 PKR",
    Rating: "4.1/5",
    Menu: 6,
    Cityid: 5,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 7,
    image: "static/images/channy.jpeg",
    name: "Murgh Channy",
    Restaurant_category_id: 2,
    Deliveryfee: "80 PKR",
    Rating: "4.2/5",
    Menu: 7,
    Cityid: 6,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 8,
    image: "static/images/paratha.jpeg",
    name: "Nashta Time",
    Restaurant_category_id: 2,
    Deliveryfee: "60 PKR",
    Rating: "4.4/5",
    Menu: 8,
    Cityid: 6,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 9,
    image: "static/images/nashta.jpeg",
    name: "Kitchen Point",
    Restaurant_category_id: 2,
    Deliveryfee: "60 PKR",
    Rating: "4.5/5",
    Menu: 9,
    Cityid: 7,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 10,
    image: "static/images/kithchen.jpeg",
    name: "Breakfast Corner",
    Restaurant_category_id: 2,
    Deliveryfee: "70 PKR",
    Rating: "4.5/5",
    Menu: 10,
    Cityid: 8,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 11,
    image: "static/images/layers.jpeg",
    name: " Layers Bakeshop",
    Restaurant_category_id: 3,
    Deliveryfee: "90 PKR",
    Rating: "4.6/5",
    Menu: 11,
    Cityid: 4,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 12,
    image: "static/images/icecream.jpeg",
    name: "Ice Food & Dry Fruits",
    Restaurant_category_id: 3,
    Deliveryfee: "80 PKR",
    Rating: "4.7/5",
    Menu: 12,
    Cityid: 15,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 13,
    image: "static/images/jalalsons_dessert.jpeg",
    name: "Jalal Sons - Cake",
    Restaurant_category_id: 3,
    Deliveryfee: "80 PKR",
    Rating: "4.7/5",
    Menu: 13,
    Cityid: 9,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 14,
    image: "static/images/cupcakes.jpeg",
    name: "Cupcakes corner - Cake",
    Restaurant_category_id: 3,
    Deliveryfee: "80 PKR",
    Rating: "4.7/5",
    Menu: 14,
    Cityid: 10,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 15,
    image: "static/images/icecream.jpeg",
    name: "Bakeshop corner ",
    Restaurant_category_id: 3,
    Deliveryfee: "80 PKR",
    Rating: "4.7/5",
    Menu: 15,
    Cityid: 3,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 16,
    image: "static/images/biryani.jpeg",
    name: "Biryani Point ",
    Restaurant_category_id: 4,
    Deliveryfee: "70 PKR",
    Rating: "4.6/5",
    Menu: 16,
    Cityid: 14,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 17,
    image: "static/images/nihari.jpeg",
    name: "Butt Karahi Tikka",
    Restaurant_category_id: 4,
    Deliveryfee: "60 PKR",
    Rating: "4.6/5",
    Menu: 17,
    Cityid: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 18,
    image: "static/images/pulao.jpeg",
    name: " Chicken Nihari",
    Restaurant_category_id: 4,
    Deliveryfee: "90 PKR",
    Rating: "4.8/5",
    Menu: 18,
    Cityid: 13,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 19,
    image: "static/images/biryani.jpeg",
    name: "Spice Bazar Model Town",
    Restaurant_category_id: 4,
    Deliveryfee: "100 PKR",
    Rating: "4.8/5",
    Menu: 13,
    Cityid: 2,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
  {
    id: 20,
    image: "static/images/nihari.jpeg",
    name: "Haveli Restaurant ",
    Restaurant_category_id: 4,
    Deliveryfee: "80 PKR",
    Rating: "4.5/5",
    Menu: 16,
    Cityid: 12,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, at consectetur totam voluptatibus quibusdam iusto. Accusamus quas, soluta ipsam autem eius necessitatibus fugiat in . ",
  },
];

export default Restaurants;
